// <auto-generated />
namespace MVC.EF.Mappings.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TabelaPessoaFisica : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabelaPessoaFisica));
        
        string IMigrationMetadata.Id
        {
            get { return "201509171605411_TabelaPessoaFisica"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
